task: "HMD_IMU_Human_Motion_Estimation"

model_name: "HMD_imu_HME_Universe"
dataset_path: "./data/preprocess/AMASS"
support_dir: "./body_models/"
resume_model: "/root/HMD-Poser-down/experiments/HMD_IMU_Human_Motion_Estimation/2025-06-30-16-15-21/epoch_with_best_testloss.pt"
manual_seed: null
compatible_inputs: ['HMD_3IMUs','HMD_2IMUs','HMD']
sparse_dim: 135
input_motion_length: 40
train_dataset_repeat_times: 1
hidden_size: 1024

train_config:
  epochs: 2000
  val_interval: 2
  num_workers: 4
  batch_size: 1
  log_interval: 5

optimizer_config:
  optimizer: "adam"
  momentum: 0.9
  beta2: 0.999
  weight_decay: 0
  adam_eps: 0.000001
  amsgrad: false

lr_config:
  lr: 0.001
  lr_decay: [300]
  lr_decay_factor: 0.1
  lr_decay_epochs: 3
  lr_warm_up_start_epoch: 0
  lr_warm_up_epochs: 1
  lr_warm_up_factor: 0.001
  lr_warm_restarts: []
  lr_warm_restart_duration: 0.5

loss:
  loss_type: 'l2'
  root_orientation_weight: 10
  local_pose_weight: 50
  global_pose_weight: 10
  joint_position_weight: 1000
  smooth_loss_weight: 5
  shape_loss_weight: 10
